[package]
name = "lab-01-brown_robinson"
version = "0.1.0"
edition = "2021"

[dependencies]
game_theory.workspace = true
brown_robinson_method.workspace = true
prettytable.workspace = true
clap = { workspace = true, features = ["derive"] }
