[package]
name = "continuous_convex_concave_method"
version.workspace = true
edition.workspace = true

[dependencies]
game_theory.workspace = true
brown_robinson_method.workspace = true
nalgebra.workspace = true
tracing = "0.1.40"
