[package]
name = "brown_robinson_method"
version.workspace = true
edition.workspace = true

[dependencies]
game_theory.workspace = true
num-traits.workspace = true
ordered-float.workspace = true
rand.workspace = true
nalgebra.workspace = true
tracing.workspace = true
